/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatAssistantItem: typeof import('./components/chat-item/chat-assistant-item.vue')['default']
    ChatHeader: typeof import('./components/chat-header.vue')['default']
    ChatInput: typeof import('./components/chat-input/chat-input.vue')['default']
    ChatInputMenu: typeof import('./components/chat-input/chat-input-menu.vue')['default']
    ChatInputMenuItem: typeof import('./components/chat-input/chat-input-menu-item.vue')['default']
    ChatItem: typeof import('./components/chat-item/chat-item.vue')['default']
    ChatLoading: typeof import('./components/chat-loading.vue')['default']
    ChatLoadingSlim: typeof import('./components/chat-loading-slim.vue')['default']
    ChatMarkdown: typeof import('./components/chat-markdown/chat-markdown.vue')['default']
    ChatNav: typeof import('./components/chat-nav/chat-nav.vue')['default']
    ChatNavLayout: typeof import('./components/chat-nav/chat-nav-layout.vue')['default']
    ChatNavTitle: typeof import('./components/chat-nav/chat-nav-title.vue')['default']
    ChatProjectSelect: typeof import('./components/chat-skill/operations/chat-project-select.vue')['default']
    ChatProjectSelectInner: typeof import('./components/chat-skill/operations/chat-project-select-inner.vue')['default']
    ChatSearchSwitch: typeof import('./components/chat-skill/operations/chat-search-switch.vue')['default']
    ChatSkillsIcon: typeof import('./components/chat-skill/chat-skills-icon.vue')['default']
    ChatSkillsList: typeof import('./components/chat-skill/chat-skills-list.vue')['default']
    ChatSkillsListButton: typeof import('./components/chat-skill/chat-skills-list-button.vue')['default']
    ChatSkillsOperationButton: typeof import('./components/chat-skill/chat-skills-operation-button.vue')['default']
    ChatSkillsOperationMenuItem: typeof import('./components/chat-skill/chat-skills-operation-menu-item.vue')['default']
    ChatSkillsSelections: typeof import('./components/chat-skill/chat-skills-selections.vue')['default']
    ChatSkillsSelectOperation: typeof import('./components/chat-skill/operations/chat-skills-select-operation.vue')['default']
    ChatThinkSwitch: typeof import('./components/chat-skill/operations/chat-think-switch.vue')['default']
    ChatUserItem: typeof import('./components/chat-item/chat-user-item.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconOperation: typeof import('./components/icon-operation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserAvatar: typeof import('./components/user-avatar.vue')['default']
  }
}

// For TSX support
declare global {
  const ChatAssistantItem: typeof import('./components/chat-item/chat-assistant-item.vue')['default']
  const ChatHeader: typeof import('./components/chat-header.vue')['default']
  const ChatInput: typeof import('./components/chat-input/chat-input.vue')['default']
  const ChatInputMenu: typeof import('./components/chat-input/chat-input-menu.vue')['default']
  const ChatInputMenuItem: typeof import('./components/chat-input/chat-input-menu-item.vue')['default']
  const ChatItem: typeof import('./components/chat-item/chat-item.vue')['default']
  const ChatLoading: typeof import('./components/chat-loading.vue')['default']
  const ChatLoadingSlim: typeof import('./components/chat-loading-slim.vue')['default']
  const ChatMarkdown: typeof import('./components/chat-markdown/chat-markdown.vue')['default']
  const ChatNav: typeof import('./components/chat-nav/chat-nav.vue')['default']
  const ChatNavLayout: typeof import('./components/chat-nav/chat-nav-layout.vue')['default']
  const ChatNavTitle: typeof import('./components/chat-nav/chat-nav-title.vue')['default']
  const ChatProjectSelect: typeof import('./components/chat-skill/operations/chat-project-select.vue')['default']
  const ChatProjectSelectInner: typeof import('./components/chat-skill/operations/chat-project-select-inner.vue')['default']
  const ChatSearchSwitch: typeof import('./components/chat-skill/operations/chat-search-switch.vue')['default']
  const ChatSkillsIcon: typeof import('./components/chat-skill/chat-skills-icon.vue')['default']
  const ChatSkillsList: typeof import('./components/chat-skill/chat-skills-list.vue')['default']
  const ChatSkillsListButton: typeof import('./components/chat-skill/chat-skills-list-button.vue')['default']
  const ChatSkillsOperationButton: typeof import('./components/chat-skill/chat-skills-operation-button.vue')['default']
  const ChatSkillsOperationMenuItem: typeof import('./components/chat-skill/chat-skills-operation-menu-item.vue')['default']
  const ChatSkillsSelections: typeof import('./components/chat-skill/chat-skills-selections.vue')['default']
  const ChatSkillsSelectOperation: typeof import('./components/chat-skill/operations/chat-skills-select-operation.vue')['default']
  const ChatThinkSwitch: typeof import('./components/chat-skill/operations/chat-think-switch.vue')['default']
  const ChatUserItem: typeof import('./components/chat-item/chat-user-item.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCollapse: typeof import('element-plus/es')['ElCollapse']
  const ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
  const ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
  const ElDrawer: typeof import('element-plus/es')['ElDrawer']
  const ElImage: typeof import('element-plus/es')['ElImage']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElPopover: typeof import('element-plus/es')['ElPopover']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
  const IconOperation: typeof import('./components/icon-operation.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const UserAvatar: typeof import('./components/user-avatar.vue')['default']
}