packages:
  - packages/*

catalog:
  '@types/file-saver': ^2.0.7
  '@types/js-md5': ^0.7.2
  '@types/lodash-es': ^4.17.12
  '@types/nprogress': ^0.2.3
  '@types/qs': ^6.14.0
  '@types/sortablejs': ^1.15.8
  '@vueuse/components': ^13.5.0
  '@vueuse/core': ^13.5.0
  axios: ^1.10.0
  chalk: ^5.4.1
  dayjs: ^1.11.13
  element-plus: ^2.11.3
  fast-xml-parser: ^5.2.5
  file-saver: ^2.0.5
  glob: ^11.0.3
  js-base64: ^3.7.8
  js-md5: ^0.8.3
  lodash-es: ^4.17.21
  minimatch: ^10.0.3
  nanoid: ^5.1.5
  nprogress: ^0.2.0
  qs: ^6.14.0
  simple-git: ^3.28.0
  sortablejs: ^1.15.6
  vditor: 3.10.7
  vue: ^3.5.13
  vue-clipboard3: ^2.0.0
  vue-router: ^4.5.1
  vue-ueditor-wrap: ^3.0.8
  xss: ^1.0.10
  zx: ^8.6.2
catalogs:
  nestjs:
    '@nestjs/cli': ^11.0.7
    '@nestjs/common': ^11.1.3
    '@nestjs/config': ^4.0.2
    '@nestjs/core': ^11.1.3
    '@nestjs/mapped-types': ^2.1.0
    '@nestjs/platform-express': ^11.1.3
    '@nestjs/schematics': ^11.0.5
    '@nestjs/swagger': ^11.2.0
    '@nestjs/testing': ^11.1.3
    '@prisma/client': ^6.13.0
    '@swc/cli': ^0.7.8
    '@swc/core': ^1.13.3
    '@types/express': ^5.0.3
    class-transformer: ^0.5.1
    class-validator: ^0.14.2
    nest-winston: ^1.10.2
    prisma: ^6.13.0
    reflect-metadata: ^0.2.2
    rxjs: ^7.8.2
    source-map-support: ^0.5.21
    swc-loader: ^0.2.6
    ts-loader: ^9.5.2
    ts-node: ^10.9.2
    tsconfig-paths: ^4.2.0
    unplugin-swc: ^1.5.5
    winston: ^3.17.0
    winston-daily-rotate-file: ^5.0.0
